services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  data_ingestion:
    build: ./Dockerfile
    environment:
      PGUSER: root
      PGPASSWORD: root
      PGHOST: pgdatabase
      PGPORT: 5432
      PGDATABASE: ny_taxi
      TAXI_TABLE: your_taxi_table_name
      TAXI_URL: your_taxi_data_url
      ZONE_TABLE: your_zone_table_name
      ZONE_URL: your_zone_data_url
    depends_on:
      - pgdatabase
    profiles:
      - ingestion
